### ISSUE TITLE
Awesome work!

### ISSUE THREAD

**Issue by trungk18** [JL978/spotify-clone-client#1]
I cloned the project and run it locally, looks great. Keep it up man!

One quick question, I couldn't see the license of that project. Would you mind if I reuse some of your code for my project (both API and some of the HTML CSS)? I also plan to build a Spotify clone with Angular for sometimes :) I will definitely credit back to this repository once I am done with my code .

Looking forward to hearing from you.

Thanks,
Trung

**Comment by warty-warthog** [comment]
yh no problem

**Comment by trungk18** [comment]
Great. Thank you!
